import { utilService } from "../../../services/util.service.js"

export const emails = [
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Miss you!',
        body: 'Would love to catch up sometimes',
        isRead: false,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'We need to rent a room for our party.',
        body: 'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan',
        isRead: false,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Be careful with that butter knife.',
        body: 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with',
        isRead: true,
        sentAt: 1557133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'The body piercing didn\'t go exactly as he expected.',
        body: 'Would love to catch up sometimes',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'That must be the tenth time I\'ve been arrested for selling deep-fried cigars.',
        body: 'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What\'s happened to me?" he thought. It wasn\'t a dream. His room, a proper human',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Two seats were vacant.',
        body: 'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'I would be delighted if the sea were full of cucumber juice.',
        body: 'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'trash',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'trash',
    },
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'binance@somemail.com',
        subject: 'Are you struggling with your Identity Verification?',
        body: 'Like other financial institutions, major cryptocurrency exchanges across the globe make identity verification mandatory in order for users to receive uninterrupted access to their services. Why is Identity verification important?',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox'
    },
    {
        id: utilService.makeId(),
        from: 'github@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1550143930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'That was how he came to win $1 million.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'grandma@hotmail.co.il',
        subject: 'Sorry I stole your car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: true,
        sentAt: 1551133630594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dr.michael63@gmail.com',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'חומצה היאלרונית היא חומר טבעי הנמצא באופן טבעי בחלקי הגוף השונים, בעיקר בעור ובמפרקים. החומצה היא בעלת יכולת לספיחת נוזלים ולמעשה מולקולה אחד של חומצה היאלורונית מסוגלת לספוג כ-500 מולקולות של מים. מכאן יכולתה של החומצה ההיאלורונית ליצור נפחים.',
        isRead: false,
        sentAt: 1651133930594,
        to: 'user@appsus.com',
        isStarred: true,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'dropbox@hotmail.co.il',
        subject: 'Your dropbox is almost at full capacity!',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'YouTube@hotmail.co.il',
        subject: 'New update, and new ways to keep track',
        body: 'We\'ve just released a new Melodics update which is action packed. One of the new features includes a new tab in the Progress Section which not only summarises how much progress you\'ve made... but how to make more progress!',
        isRead: false,
        sentAt: 1561133430594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'facebook@hotmail.co.il',
        subject: 'NadavVazana invited you to NadavVazana/TravelTip',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1551133930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'netflix@hotmail.co.il',
        subject: 'Come watch out new shows',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541135930594,
        to: 'user@appsus.com',
        isStarred: false,
        status: 'inbox',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Miss you!',
        body: 'Would love to catch up sometimes',
        isRead: false,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'We need to rent a room for our party.',
        body: 'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan',
        isRead: false,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Be careful with that butter knife.',
        body: 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with',
        isRead: true,
        sentAt: 1557133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'The body piercing didn\'t go exactly as he expected.',
        body: 'Would love to catch up sometimes',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'That must be the tenth time I\'ve been arrested for selling deep-fried cigars.',
        body: 'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What\'s happened to me?" he thought. It wasn\'t a dream. His room, a proper human',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'user@appsus.com',
        subject: 'Two seats were vacant.',
        body: 'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave',
        isRead: true,
        sentAt: 1551133930594,
        to: 'momo@momo.com',
        isStarred: true,
        status: 'sent',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'I would be delighted if the sea were full of cucumber juice.',
        body: 'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'draft',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'trash',
    },
    {
        id: utilService.makeId(),
        from: 'me@appsus.com',
        subject: 'Why did you steal my car',
        body: 'You can accept or decline this invitation. You can also head over to https://github.com/NadavVazana/TravelTip to check out the repository or visit @NadavVazana to learn a bit more about them. This invitation will expire in 7 days.',
        isRead: false,
        sentAt: 1541133930594,
        to: 'grandma@hotmail.co.il',
        isStarred: false,
        status: 'trash',
    },
]
